Feature/teammodal
KurbatovAS/project6 pull request #19
Opened 2022-01-17 18:19 UTC by Lelyak-Andriy

Андрей, посмотри, пожалуйста.

2022-01-17 23:52 UTC, KurbatovAS requested changes
Андрюха, в целом всё хорошо, но нужно некоторые мелкие правки сделать. Что и где я указал в комментариях. Рекомендация от Репеты и просьба от меня. На каждый комментарий пиши какой-то ответ. Если сделал правки - можешь написать "Исправил/сделал/почее", если в конкретном случае по твоему мнению правок делать тут не нужно, то отпиши, к примеру - "Считаю, что тут и так хорошо :) или типа того"

2022-01-17 23:52 UTC, KurbatovAS commented on src/sass/components/_team-modal.scss
> +    flex-wrap: wrap;
В этом медиа правиле "flex-wrap: wrap;" уже не нужен. Он унаследуется с "таблеточного" медиаправила

2022-01-17 23:52 UTC, KurbatovAS commented on src/sass/components/_team-modal.scss
> +  transition: opacity 250ms cubic-bezier(0.4, 0, 0.2, 1);
Посмотри в переменных, может есть переменная/переменные для таких параметров css перехода. Если нет, то можешь создать и через переменную прописать.

2022-01-17 23:52 UTC, KurbatovAS commented on src/sass/components/_team-modal.scss
> +  background-color: rgba(0, 0, 0, 0.2);
Этот цвет (и другие, если он/они встречается более, чем один раз) лучше прописать через переменную.

2022-01-17 23:52 UTC, KurbatovAS commented on src/sass/components/_team-modal.scss
> +  transition: transform 250ms cubic-bezier(0.4, 0, 0.2, 1);
Опять же тут посмотри, может сделать через переменную?

2022-01-17 23:52 UTC, KurbatovAS commented on src/sass/components/_team-modal.scss
> +  transition: fill 250ms cubic-bezier(0.4, 0, 0.2, 1);
Может быть и тут.

2022-01-17 23:52 UTC, KurbatovAS commented on src/sass/components/_team-modal.scss
> +  font-weight: 400;
Как правило "**font-weight: 400;**" - это значение по умолчанию, потому в подавляющем большинстве случаев его переопределять нет надобности. Можешь проверить - закомментируй его, если ничего не измениться, то можешь его удалить.

2022-01-17 23:52 UTC, KurbatovAS commented on src/sass/components/_team-modal.scss
> +  background:#ffffff;
Для этого цвета у нас есть переменная "**$main-color**"

2022-01-17 23:52 UTC, KurbatovAS commented on src/sass/components/_team-modal.scss
> +  transition: background 250ms cubic-bezier(0.4, 0, 0.2, 1);
Тут тоже может стоит через переменную прописать?

2022-01-17 23:52 UTC, KurbatovAS commented on src/sass/components/_team-modal.scss
> +  fill:#ffffff;
Переменная тут и просмотри дальше.

2022-01-17 23:52 UTC, KurbatovAS commented on src/partials/team-modal.html
> +            <h2 class="team__title">Наша команда</h2>
Ты этим классом "**team__title**" создаешь новый блок или он должен был быть элементов какого-то другого блока? Посмотри, правильно ли ты указал имя класса для этого элемента.

2022-01-18 13:24 UTC, Lelyak-Andriy commented on src/sass/components/_team-modal.scss
> +    flex-wrap: wrap;
исправил

2022-01-18 13:25 UTC, Lelyak-Andriy commented on src/sass/components/_team-modal.scss
> +  transition: opacity 250ms cubic-bezier(0.4, 0, 0.2, 1);
исправил

2022-01-18 13:25 UTC, Lelyak-Andriy commented on src/sass/components/_team-modal.scss
> +  background-color: rgba(0, 0, 0, 0.2);
исправил

2022-01-18 13:25 UTC, Lelyak-Andriy commented on src/sass/components/_team-modal.scss
> +  transition: transform 250ms cubic-bezier(0.4, 0, 0.2, 1);
исправил

2022-01-18 13:25 UTC, Lelyak-Andriy commented on src/sass/components/_team-modal.scss
> +  transition: fill 250ms cubic-bezier(0.4, 0, 0.2, 1);
исправил

2022-01-18 13:25 UTC, Lelyak-Andriy commented on src/sass/components/_team-modal.scss
> +  font-weight: 400;
Да, точно! исправил

2022-01-18 13:25 UTC, Lelyak-Andriy commented on src/sass/components/_team-modal.scss
> +  background:#ffffff;
исправил

2022-01-18 13:25 UTC, Lelyak-Andriy commented on src/sass/components/_team-modal.scss
> +  transition: background 250ms cubic-bezier(0.4, 0, 0.2, 1);
исправил

2022-01-18 13:25 UTC, Lelyak-Andriy commented on src/sass/components/_team-modal.scss
> +  fill:#ffffff;
исправил

2022-01-18 13:25 UTC, Lelyak-Andriy commented on src/partials/team-modal.html
> +            <h2 class="team__title">Наша команда</h2>
исправил

2022-01-18 13:25 UTC, Lelyak-Andriy commented
все исправил

2022-01-18 17:32 UTC, KurbatovAS approved these changes

2022-01-18 17:32 UTC, merged